### ISSUE TITLE
Request for Fcm InstanceId and Token failed (Fcm FIS_AUTH_ERROR)

### ISSUE THREAD

**Issue by Siavoosh** [pusheco/pushe-android-studio-sample#29]
```
03-02 03:14:16.884 30981-30981/com.long_tongue.app E/Pushe: co.pushe.plus.messaging.fcm.FcmTokenException: Request for Fcm InstanceId and Token failed
        at co.pushe.plus.messaging.fcm.FcmTokenStore$b$1.onComplete(FcmTokenStore.kt:73)
        at com.google.android.gms.tasks.zzj.run(Unknown Source)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:7223)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
     Caused by: java.io.IOException: FIS_AUTH_ERROR
        at com.google.firebase.iid.zzs.zza(com.google.firebase:firebase-iid@@20.1.0:82)
        at com.google.firebase.iid.zzs.zza(com.google.firebase:firebase-iid@@20.1.0:96)
        at com.google.firebase.iid.zzx.then(com.google.firebase:firebase-iid@@20.1.0:4)
        at com.google.android.gms.tasks.zzd.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
```

**Comment by mahdi-malv** [comment]
<div dir='rtl'>

سلام
خطای ` Request for Fcm InstanceId and Token failed` زمانی رخ می‌ده که پوشه قصد داره بررسی کنه که رجیستری که انجام شده و ذخیره شده درست هست یا نه. تو این حالت از فایربیس درخواست token می‌کنه که اگر این مورد به مشکل بخوره و پوشه نتونه کاریش کنه این خطا رخ می‌ده.
برای حل این خطا باید ببینید چرا فایربیس نتونسته توکن رو برگردونه

لطفا لایبرری‌های فایربیسی که استفاده کردید و نسخه‌ی اونها که رو بگید و همچنین نسخه‌ی پوشه‌ای که در برنامه اضافه‌کردید

</div>

**Comment by mahdi-malv** [comment]
<div dir='rtl'>

سلام مجدد

خطای ذکر شده بخاطر ورژن ۲۰.۱.۱ به بالای فایربیس هست که ناسازگاری با لایبرری پوشه داره.
سریع‌ترین راه‌حل اینه ورژن رو بالاتر از ۲۰.۱.۰ نبرید.

این مشکل رو برای نسخه‌های آتی حل خواهیم کرد.
ممنون

</div>

[Firebase release note](https://firebase.google.com/support/release-notes/android#messaging_v20-1-1)

**Comment by mahdi-malv** [comment]
<div dir='rtl'>

مشکل توی نسخه‌ی **2.1.0** به بعد پوشه حل شده و از این نسخه به بعد محدودیتی روی نسخه‌ی فایربیس وجود ندارد.

</div>
