### ISSUE TITLE
No virtual method throttleLatest

### ISSUE THREAD

**Issue by mahdi-malv** [pusheco/pushe-android-studio-sample#30]
### To reproduce

Exclude custom `RxJava`

```groovy
implementation ('co.pushe.plus:base:2.0.4') {
   exclude group: 'co.pushe.plus', module: 'rxjava'
}
implementation 'io.reactivex.rxjava2:rxjava:2.1.9'
```

### Error stacktrace

```
java.lang.NoSuchMethodError: No virtual method throttleLatest(JLjava/util/concurrent/TimeUnit;Lio/reactivex/Scheduler;Z)Lio/reactivex/Observable; in class Lco/pushe/plus/utils/rx/PublishRelay; or its super classes (declaration of 'co.pushe.plus.utils.rx.PublishRelay' appears in /data/app/com.banimode.testpusheplus-ZCQAvR1ZRFUgnbfUk2hPdw==/base.apk)
        at co.pushe.plus.UserCredentials.<init>(UserCredentials.kt:29)
        at co.pushe.plus.o.get(UserCredentials_Factory.java:1017)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at co.pushe.plus.messaging.f.get(ParcelStamper_Factory.java:1035)
        at co.pushe.plus.messaging.h.get(PostOffice_Factory.java:1038)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at co.pushe.plus.dagger.f.messageDispatcher(DaggerCoreComponent.java:224)
        at co.pushe.plus.CoreInitializer.preInitialize(PusheInit.kt:42)
        at co.pushe.plus.internal.PusheInitializer.preInitializeComponents(PusheInitializer.kt:73)
        at co.pushe.plus.internal.PusheInitializer.initialize(PusheInitializer.kt:18)
        at co.pushe.plus.utils.InitProvider.onCreate(InitProvider.kt:13)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1940)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1915)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6755)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6302)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6217)
        at android.app.ActivityThread.access$1200(ActivityThread.java:237)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1792)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7063)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
```

**Comment by mahdi-malv** [comment]
<div dir='rtl'>

متد `throttleLatest`در نسخه‌ی ۲.۲.۰ لایبرری RxJava2 اضافه شده و در صورتی که نسخه‌ی کمتری رو برای override کردن اضافه کنید این متد وجود نخواهد داشت و لایبرری پوشه با خطا مواجه میشه.

برای حل این مورد بایستی نسخه‌ی ۲.۲.۰ به بالای RxJava رو اضافه کنید.

</div>

```groovy
implementation ('co.pushe.plus:base:2.0.4') {
   exclude group: 'co.pushe.plus', module: 'rxjava'
}
implementation 'io.reactivex.rxjava2:rxjava:2.2.9' // latest at the time
```

> در نظر داشته باشید که باید **RxJava2** رو اضافه کنید و **RxJava3** متفاوت هست.

**TL; DR**

Use **RxJava2** with version atleast 2.2.0

[RxJava release note](https://github.com/ReactiveX/RxJava/releases/tag/v2.2.0)
