### ISSUE TITLE
Invalid pushe_token provided in application manifest

### ISSUE THREAD

**Issue by hengamehgithub** [pusheco/pushe-android-studio-sample#40]
سلام بنده تگ متا رو دقیقا جای درست قرار دادم اما هنگام بیلد این خطا رو میگیرم
E/Pushe: Could not initialize Pushe     
co.pushe.plus.PusheManifestException: Invalid pushe_token provided in application manifest

**Comment by hengamehgithub** [comment]
at co.pushe.plus.AppManifest.extractManifestData(AppManifest.kt:421)
        at co.pushe.plus.CoreInitializer.preInitialize(PusheInit.kt:12)
        at co.pushe.plus.internal.PusheInitializer.preInitializeComponents(PusheInitializer.kt:74)
        at co.pushe.plus.internal.PusheInitializer.initialize(PusheInitializer.kt:2)
        at co.pushe.plus.utils.InitProvider.onCreate(InitProvider.kt:13)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1751)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1726)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6211)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5729)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5647)
        at android.app.ActivityThread.-wrap2(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1637)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:156)

**Comment by mahdi-malv** [comment]
<div dir='rtl'>

سلام
خطا اشاره به این داره که توکنی که قراردادید درست نیست
لطفا بررسی کنید توکن به طور کامل کپی شده باشه و بدون مشکل باشه

در صورتی که باز هم کار نکرد لطفا اطلاعات برنامه‌تون رو به پشتیبانی اطلاع بدید تا بررسی کنن.

با تشکر.

</div>
