### ISSUE TITLE
: Error trying to retrieve fragment's id name. Ignoring the  fragment -  Unable to find resource ID

### ISSUE THREAD

**Issue by Mohadese267** [pusheco/pushe-android-studio-sample#77]
`2022-07-30 15:48:16.531 4898-4898/com.example.LingoFellow I/Pushe: Starting Pushe initialization
2022-07-30 15:48:16.812 4898-4898/com.example.LingoFellow D/[Pushe]: Sentry is turned off in the settings or no dsn was set
2022-07-30 15:48:17.327 4898-4976/com.example.LingoFellow I/FirebaseApp: Device unlocked: initializing all Firebase APIs for app Pushe
2022-07-30 15:48:18.515 4898-4971/com.example.LingoFellow I/Pushe: Registration is required, performing registration
2022-07-30 15:48:18.910 4898-4971/com.example.LingoFellow I/Pushe: Creating default notification channel
2022-07-30 15:48:18.995 4898-4971/com.example.LingoFellow I/Pushe: Pushe initialization complete
2022-07-30 15:48:21.825 4898-4971/com.example.LingoFellow I/Pushe: Registration successful
2022-07-30 15:48:22.413 4898-4977/com.example.LingoFellow I/WM-WorkerWrapper: Worker result SUCCESS for Work [ id=2d920d64-83a3-4d6c-8180-8fbc4d234994, tags={ co.pushe.plus.internal.task.PusheTaskPerformer, pushe, pushe_collection_hidden_app } ]
2022-07-30 15:48:22.499 4898-4991/com.example.LingoFellow I/WM-WorkerWrapper: Worker result SUCCESS for Work [ id=04cfe542-725e-4ea9-854d-4f0bfa4e0dc7, tags={ co.pushe.plus.internal.task.PusheTaskPerformer, pushe_collection_cell_info, pushe } ]
2022-07-30 15:48:22.564 4898-4991/com.example.LingoFellow I/WM-WorkerWrapper: Worker result SUCCESS for Work [ id=fb174aed-b229-41e2-892e-ed9ca69ea5bd, tags={ co.pushe.plus.internal.task.PusheTaskPerformer, pushe, pushe_collection_constant_data } ]
2022-07-30 15:48:22.601 4898-4991/com.example.LingoFellow I/WM-WorkerWrapper: Worker result SUCCESS for Work [ id=3ce79ca0-fc8b-46b7-8e0b-e8cbd0c43bb0, tags={ co.pushe.plus.internal.task.PusheTaskPerformer, pushe_collection_variable_data, pushe } ]
2022-07-30 15:48:22.629 4898-4977/com.example.LingoFellow I/WM-WorkerWrapper: Worker result SUCCESS for Work [ id=5ace243c-8efc-4bb0-bc86-a453d7799550, tags={ co.pushe.plus.internal.task.PusheTaskPerformer, pushe_collection_wifi_list, pushe } ]
2022-07-30 15:48:28.985 4898-5010/com.example.LingoFellow I/WM-WorkerWrapper: Worker result SUCCESS for Work [ id=ef045c73-3f98-4ea8-bdca-d16737353be7, tags={ co.pushe.plus.internal.task.PusheTaskPerformer, pushe, pushe_upstream_flush } ]
2022-07-30 15:48:48.791 4898-5010/com.example.LingoFellow I/WM-WorkerWrapper: Worker result SUCCESS for Work [ id=569ac9ba-8ac6-4edf-9b41-077b1ecc2391, tags={ co.pushe.plus.internal.task.PusheTaskPerformer, pushe, pushe_registration } ]
2022-07-30 15:48:52.486 4898-5013/com.example.LingoFellow I/WM-WorkerWrapper: Worker result SUCCESS for Work [ id=7a2cfb0b-ea71-4b3a-94bb-7a63aff232d9, tags={ co.pushe.plus.internal.task.PusheTaskPerformer, pushe_collection_floating_data, pushe } ]
2022-07-30 15:49:22.710 4898-4898/com.example.LingoFellow E/Pushe: Error trying to retrieve fragment's id name. Ignoring the fragment
    android.content.res.Resources$NotFoundException: Unable to find resource ID #0x3b
        at android.content.res.ResourcesImpl.getResourceEntryName(ResourcesImpl.java:300)
        at android.content.res.Resources.getResourceEntryName(Resources.java:2112)
        at co.pushe.plus.analytics.b.b(AppLifecycleListener.kt:23)
        at co.pushe.plus.analytics.b.b(AppLifecycleListener.kt:1)
        at co.pushe.plus.analytics.-$$Lambda$qQPFkKoqSiQ8t_Sdb419j77a-L4.apply(Unknown Source:4)
        at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:57)
        at co.pushe.plus.utils.rx.BehaviorRelay$BehaviorDisposable.test(BehaviorRelay.java:2)
        at co.pushe.plus.utils.rx.BehaviorRelay$BehaviorDisposable.emitNext(BehaviorRelay.java:28)
        at co.pushe.plus.utils.rx.BehaviorRelay.accept(BehaviorRelay.java:3)
        at co.pushe.plus.analytics.d.onFragmentResumed(AppLifecycleNotifier.kt:49)
        at androidx.fragment.app.FragmentLifecycleCallbacksDispatcher.dispatchOnFragmentResumed(FragmentLifecycleCallbacksDispatcher.java:208)
        at androidx.fragment.app.FragmentStateManager.resume(FragmentStateManager.java:606)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:285)
        at androidx.fragment.app.SpecialEffectsController$FragmentStateManagerOperation.complete(SpecialEffectsController.java:771)
        at androidx.fragment.app.SpecialEffectsController$Operation.completeSpecialEffect(SpecialEffectsController.java:690)
        at androidx.fragment.app.DefaultSpecialEffectsController$SpecialEffectsInfo.completeSpecialEffect(DefaultSpecialEffectsController.java:855)
        at androidx.fragment.app.DefaultSpecialEffectsController.startAnimations(DefaultSpecialEffectsController.java:154)
        at androidx.fragment.app.DefaultSpecialEffectsController.executeOperations(DefaultSpecialEffectsController.java:123)
        at androidx.fragment.app.SpecialEffectsController.executePendingOperations(SpecialEffectsController.java:306)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1853)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1764)
        at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1670)
        at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:323)
        at com.swmansion.rnscreens.ScreenContainer.onUpdate(ScreenContainer.kt:350)
        at com.swmansion.rnscreens.ScreenContainer.performUpdates(ScreenContainer.kt:299)
        at com.swmansion.rnscreens.ScreenContainer.performUpdatesNow(ScreenContainer.kt:291)
        at com.swmansion.rnscreens.ScreenContainer.setFragmentManager(ScreenContainer.kt:135)
        at com.swmansion.rnscreens.ScreenContainer.setupFragmentManager(ScreenContainer.kt:170)
        at com.swmansion.rnscreens.ScreenContainer.onAttachedToWindow(ScreenContainer.kt:199)
        at android.view.View.dispatchAttachedToWindow(View.java:20105)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3430)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
        at android.view.ViewGroup.addViewInner(ViewGroup.java:5193)
        at android.view.ViewGroup.addView(ViewGroup.java:4979)
        at com.facebook.react.views.view.ReactViewGroup.addView(ReactViewGroup.java:466)
        at android.view.ViewGroup.addView(ViewGroup.java:4919)
        at com.facebook.react.uimanager.ViewGroupManager.addView(ViewGroupManager.java:37)
        at com.facebook.react.uimanager.NativeViewHierarchyManager.manageChildren(NativeViewHierarchyManager.java:533)
        at com.facebook.react.uimanager.UIViewOperationQueue$ManageChildrenOperation.execute(UIViewOperationQueue.java:217)
        at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:915)
        at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1026)
2022-07-30 15:49:22.713 4898-4898/com.example.LingoFellow E/Pushe:     at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:47)
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1086)
        at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:965)
        at android.view.Choreographer.doCallbacks(Choreographer.java:791)
        at android.view.Choreographer.doFrame(Choreographer.java:722)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
` این خطا زمان اجرای برنامه در اندروید 10 ایجاد میشه ، دستگاه هم در کنسول رجیستر نمیشه با وجود این که اینجا میزنه انجام شده رجیستریشن

**Comment by Mohadese267** [comment]
این ارور فقط زمان اولین نصب وجود داره و بعد از اون که اپ رو اجرا میکنم  به این وضعیت تغییر پیدا میکنه 
![image](https://user-images.githubusercontent.com/35900178/181909257-a7ec846e-703e-452e-9fd7-3b587d7282f4.png)
