### ISSUE TITLE
Error No available courier is found

### ISSUE THREAD

**Issue by mahmoodkarimizade** [pusheco/pushe-android-studio-sample#81]
No available service
2022-12-08 16:39:56.000 30735-30796 Pushe                   com.stspmlm.stsmlm                   E  Pushe core module could not initialize
2022-12-08 16:39:56.000 30735-30796 Pushe                   com.stspmlm.stsmlm                   E  Calling postInit of core FAILED
2022-12-08 16:39:56.007 30735-30796 Pushe                   com.stspmlm.stsmlm                   E  co.pushe.plus.messaging.NoAvailableCourierException: No available courier is found
                                                                                                    	at co.pushe.plus.RegistrationManager.a(RegistrationManager.kt:7)
                                                                                                    	at co.pushe.plus.RegistrationManager$$ExternalSyntheticLambda11.subscribe(Unknown Source:2)
                                                                                                    	at io.reactivex.internal.operators.completable.CompletableAndThenCompletable$SourceObserver.onComplete(CompletableAndThenCompletable.java:67)
                                                                                                    	at io.reactivex.internal.operators.single.SingleFlatMapCompletable$FlatMapCompletableObserver.onComplete(SingleFlatMapCompletable.java:102)
                                                                                                    	at io.reactivex.internal.operators.completable.CompletableFromCallable.subscribeActual(CompletableFromCallable.java:47)
                                                                                                    	at io.reactivex.Completable.subscribe(Completable.java:2309)
                                                                                                    	at io.reactivex.internal.operators.single.SingleFlatMapCompletable$FlatMapCompletableObserver.onSuccess(SingleFlatMapCompletable.java:91)
                                                                                                    	at io.reactivex.internal.operators.observable.ObservableToListSingle$ToListObserver.onComplete(ObservableToListSingle.java:111)
                                                                                                    	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeOnObserver.onComplete(ObservableSubscribeOn.java:68)
                                                                                                    	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.checkTerminated(ObservableObserveOn.java:287)
                                                                                                    	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:172)
                                                                                                    	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
                                                                                                    	at co.pushe.plus.internal.c.a(Schedulers.kt:1)
                                                                                                    	at co.pushe.plus.internal.c$$ExternalSyntheticLambda0.run(Unknown Source:4)
                                                                                                    	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:288)
                                                                                                    	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:253)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)

**Comment by prog47** [comment]
Hi, Thanks for your services.
I have this issue also. All notifications receive but subscription to tags and topics not working and callbacks not triggered.
compileSdk 32
minSdk 21
targetSdk 32
'co.pushe.plus:base:2.6.3'

Thank you
