### ISSUE TITLE
io.reactivex.exceptions.UndeliverableException

### ISSUE THREAD

**Issue by ektefa** [pusheco/pushe-android-studio-sample#83]
This is a log from my crashlytics. It happens on almost every device brands and android versions.
Sometimes its caused by
```java.net.ConnectException: Failed to connect to ip-alt.pushe.co/162.243.147.245:443```
and sometimes its
```javax.net.ssl.SSLHandshakeException: Connection closed by peer```

**Full log**
```
io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.net.ConnectException: Failed to connect to ip-alt.pushe.co/162.243.147.245:443
at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:42)
at io.reactivex.internal.operators.single.SingleToObservable$SingleToObservableObserver.onError(SingleToObservable.java:9)
at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onError(SingleMap.java:3)
at io.reactivex.internal.operators.single.SingleCreate$Emitter.tryOnError(SingleCreate.java:28)
at co.pushe.plus.utils.HttpUtils$$ExternalSyntheticLambda0.subscribe(R8$$SyntheticClass:45)
at io.reactivex.internal.operators.single.SingleCreate.subscribeActual(SingleCreate.java:11)
at io.reactivex.Single.subscribe(Single.java:3)
at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:10)
at io.reactivex.Single.subscribe(Single.java:3)
at io.reactivex.internal.operators.single.SingleToObservable.subscribeActual(SingleToObservable.java:8)
at io.reactivex.Observable.subscribe(Observable.java:3)
at io.reactivex.internal.operators.observable.ObservableDoOnEach.subscribeActual(ObservableDoOnEach.java:18)
at io.reactivex.Observable.subscribe(Observable.java:3)
at io.reactivex.internal.operators.observable.ObservableOnErrorNext.subscribeActual(ObservableOnErrorNext.java:17)
at io.reactivex.Observable.subscribe(Observable.java:3)
at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.subscribeInner(ObservableFlatMap.java:201)
at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.onNext(ObservableFlatMap.java:49)
at io.reactivex.internal.operators.observable.ObservableFromIterable.subscribeActual(ObservableFromIterable.java:52)
at io.reactivex.Observable.subscribe(Observable.java:3)
at io.reactivex.internal.operators.observable.ObservableFlatMap.subscribeActual(ObservableFlatMap.java:27)
at io.reactivex.Observable.subscribe(Observable.java:3)
at io.reactivex.internal.operators.observable.ObservableElementAtMaybe.subscribeActual(ObservableElementAtMaybe.java:10)
at io.reactivex.Maybe.subscribe(Maybe.java:3)
at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeTask.run(MaybeSubscribeOn.java:5)
at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:10)
at co.pushe.plus.internal.c$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:15)
at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.j
ava:11)
at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:38)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
at java.lang.Thread.run(Thread.java:784)
Caused by: java.net.ConnectException: Failed to connect to ip-alt.pushe.co/162.243.147.245:443
at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:143)
at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:538)
at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(Unknown Source:0)
at co.pushe.plus.utils.HttpUtils.requestBlocking(HttpUtils.kt:121)
at co.pushe.plus.utils.HttpUtils$$ExternalSyntheticLambda0.subscribe(R8$$SyntheticClass:36)
```

**Comment by mahdi-malv** [comment]
Former contributor here
The main reason of the exception is 
```
Caused by: java.net.ConnectException: Failed to connect to ip-alt.pushe.co/162.243.147.245:443
```

Meaning that all public IP fetch websites have failed eventually.

Luckily, there's a way to add a priority IP fetcher using this manifest flag

```xml
<meta-data
            android:name="pushe_public_ip_endpoint"
            android:value="https://api.ipify.org/?format=json" />
```
simply put it in `AndroidManifest.xml` file (next to `pushe_token`)

For instance `ip.ipify` seems to be working for me.

> Hint
> Pushe uses public IP to determine their approximate country for the main panel in console.pushe.co
