### ISSUE TITLE
Error trying to update fragment duration in sessionFlow

### ISSUE THREAD

**Issue by mhchofficial** [pusheco/pushe-android-studio-sample#84]
hi i use     
implementation 'co.pushe.plus:base:2.6.4'

   minSdk 22
  targetSdk 33
  versionCode 1
  versionName "1.0"

but i send push notif from pushe console but not displaying 

Logcat error:

```
Error trying to update fragment duration in sessionFlow
                                                                                                    java.lang.NullPointerException: The mapper function returned a null value.
                                                                                                    	at io.reactivex.internal.functions.ObjectHelper.requireNonNull(ObjectHelper.java:39)
                                                                                                    	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:57)
                                                                                                    	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64)
                                                                                                    	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64)
                                                                                                    	at io.reactivex.internal.operators.single.SingleJust.subscribeActual(SingleJust.java:30)
                                                                                                    	at io.reactivex.Single.subscribe(Single.java:3666)
                                                                                                    	at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
                                                                                                    	at io.reactivex.Single.subscribe(Single.java:3666)
                                                                                                    	at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
                                                                                                    	at io.reactivex.Single.subscribe(Single.java:3666)
                                                                                                    	at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
                                                                                                    	at io.reactivex.Single.subscribe(Single.java:3666)
                                                                                                    	at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
                                                                                                    	at io.reactivex.Single.subscribe(Single.java:3666)
                                                                                                    	at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
                                                                                                    	at io.reactivex.Single.subscribe(Single.java:3666)
                                                                                                    	at io.reactivex.internal.operators.completable.CompletableFromSingle.subscribeActual(CompletableFromSingle.java:29)
                                                                                                    	at io.reactivex.Completable.subscribe(Completable.java:2309)
                                                                                                    	at io.reactivex.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51)
                                                                                                    	at io.reactivex.Completable.subscribe(Completable.java:2309)
                                                                                                    	at io.reactivex.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51)
                                                                                                    	at io.reactivex.Completable.subscribe(Completable.java:2309)
                                                                                                    	at io.reactivex.internal.operators.completable.CompletableOnErrorComplete.subscribeActual(CompletableOnErrorComplete.java:35)
                                                                                                    	at io.reactivex.Completable.subscribe(Completable.java:2309)
                                                                                                    	at io.reactivex.internal.operators.observable.ObservableFlatMapCompletableCompletable$FlatMapCompletableMainObserver.onNext(ObservableFlatMapCompletableCompletable.java:110)
                                                                                                    	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
                                                                                                    	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
                                                                                                    	at co.pushe.plus.internal.c.a(Schedulers.kt:1)
                                                                                                    	at co.pushe.plus.internal.c$$ExternalSyntheticLambda0.run(Unknown Source:4)
                                                                                                    	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:288)
                                                                                                    	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:253)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    	at java.lang.Thread.run(Thread.java:919)
```

**Comment by mhchofficial** [comment]
```
E/Pushe: Error trying to update fragment duration in sessionFlow
    co.pushe.plus.analytics.AnalyticsException: Invalid last activity
        at co.pushe.plus.analytics.session.a.a(SessionFlowManager.kt:168)
        at co.pushe.plus.analytics.session.a.c(SessionFlowManager.kt:34)
        at co.pushe.plus.analytics.session.a$$ExternalSyntheticLambda21.apply(Unknown Source:4)
        at io.reactivex.internal.operators.observable.ObservableFlatMapCompletableCompletable$FlatMapCompletableMainObserver.onNext(ObservableFlatMapCompletableCompletable.java:97)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
        at co.pushe.plus.internal.c.a(Schedulers.kt:1)
        at co.pushe.plus.internal.c$$ExternalSyntheticLambda0.run(Unknown Source:4)
        at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:288)
        at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:253)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```
