### ISSUE TITLE
Android 14 Upgrade Change List

### ISSUE THREAD

**Issue by SaeedBahari** [pusheco/pushe-android-studio-sample#86]
متاسفانه کتابخانه بر روی اندروید های 14 به دلیل تغییرات در نحوه رجیستر کردن broadcast ها کار نمیکنه.
پیغام نمایشی:

java.lang.SecurityException: ***packageName****: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
                                                                            	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
                                                                            	at android.os.Parcel.createException(Parcel.java:3041)
                                                                            	at android.os.Parcel.readException(Parcel.java:3024)
                                                                            	at android.os.Parcel.readException(Parcel.java:2966)
                                                                            	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5684)
                                                                            	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1852)
                                                                            	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1792)
                                                                            	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1780)
                                                                            	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:755)
                                                                            	at co.pushe.plus.notification.NotificationInitializer.a(PusheInit.kt:22)
                                                                            	at co.pushe.plus.notification.NotificationInitializer$$ExternalSyntheticLambda1.call(Unknown Source:4)
                                                                            	at io.reactivex.internal.operators.completable.CompletableFromCallable.subscribeActual(CompletableFromCallable.java:36)
                                                                            	at io.reactivex.Completable.subscribe(Completable.java:2309)
                                                                            	at io.reactivex.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51)
                                                                            	at io.reactivex.Completable.subscribe(Completable.java:2309)
                                                                            	at io.reactivex.internal.operators.mixed.ObservableConcatMapCompletable$ConcatMapCompletableObserver.drain(ObservableConcatMapCompletable.java:265)
                                                                            	at io.reactivex.internal.operators.mixed.ObservableConcatMapCompletable$ConcatMapCompletableObserver.innerComplete(ObservableConcatMapCompletable.java:203)
                                                                            	at io.reactivex.internal.operators.mixed.ObservableConcatMapCompletable$ConcatMapCompletableObserver$ConcatMapInnerObserver.onComplete(ObservableConcatMapCompletable.java:294)
                                                                            	at io.reactivex.internal.operators.completable.CompletablePeek$CompletableObserverImplementation.onComplete(CompletablePeek.java:115)
                                                                            	at io.reactivex.internal.operators.completable.CompletableAndThenCompletable$NextObserver.onComplete(CompletableAndThenCompletable.java:99)
                                                                            	at co.pushe.plus.CoreInitializer.a(PusheInit.kt:33)
                                                                            	at co.pushe.plus.CoreInitializer$$ExternalSyntheticLambda2.subscribe(Unknown Source:4)
                                                                            	at io.reactivex.internal.operators.completable.CompletableAndThenCompletable$SourceObserver.onComplete(CompletableAndThenCompletable.java:67)
                                                                            	at io.reactivex.internal.operators.completable.CompletableObserveOn$ObserveOnCompletableObserver.run(CompletableObserveOn.java:89)
                                                                            	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
                                                                            	at co.pushe.plus.internal.c.a(Schedulers.kt:1)
                                                                            	at co.pushe.plus.internal.c$$ExternalSyntheticLambda0.run(Unknown Source:4)
                                                                            	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:288)
                                                                            	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:253)
                                                                            	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                            	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                            	at java.lang.Thread.run(Thread.java:1012)
                                                                            Caused by: android.os.RemoteException: Remote stack trace:
                                                                            	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:13927)
                                                                            	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2570)
                                                                            	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2720)
                                                                            	at android.os.Binder.execTransactInternal(Binder.java:1339)
                                                                            	at android.os.Binder.execTransact(Binder.java:1275)

**Comment by SaeedBahari** [comment]
نسخه مورد استفاده 2.6.4 می باشد که متاسفانه برای این مورد تغییرات مورد نظر اعمال نشده است.
